import {
  clearSessionCookie,
  createSessionCookie,
  ensureFreshSession,
  isStravaConfigured,
} from "../_lib/strava.js";

export const config = {
  api: {
    bodyParser: {
      sizeLimit: "2mb",
    },
  },
};

export default async function handler(req, res) {
  if (req.method !== "POST") {
    res.setHeader("Allow", "POST");
    res.status(405).json({ error: "Method not allowed." });
    return;
  }

  if (!isStravaConfigured(req)) {
    res.status(503).json({ error: "Strava is not configured on this deployment." });
    return;
  }

  try {
    const { session, refreshed } = await ensureFreshSession(req);
    if (!session?.accessToken) {
      res.setHeader("Set-Cookie", clearSessionCookie());
      res.status(401).json({ error: "Connect Strava before uploading a route." });
      return;
    }

    const { gpx, name, description } = req.body || {};
    if (typeof gpx !== "string" || !gpx.trim()) {
      res.status(400).json({ error: "Missing GPX payload." });
      return;
    }

    const uploadName = typeof name === "string" && name.trim() ? name.trim() : "Routa Route";
    const form = new FormData();
    form.append("name", uploadName);
    form.append("description", typeof description === "string" ? description : "Route generated by Routa.");
    form.append("data_type", "gpx");
    form.append("external_id", `routa-${Date.now()}.gpx`);
    form.append(
      "file",
      new Blob([gpx], { type: "application/gpx+xml" }),
      `${uploadName.replace(/\s+/g, "_")}.gpx`,
    );

    const uploadResponse = await fetch("https://www.strava.com/api/v3/uploads", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${session.accessToken}`,
      },
      body: form,
    });
    const uploadData = await uploadResponse.json();

    if (!uploadResponse.ok) {
      res.status(uploadResponse.status).json({
        error: uploadData.message || "Strava upload failed.",
        details: uploadData.errors || null,
      });
      return;
    }

    if (refreshed) {
      res.setHeader("Set-Cookie", createSessionCookie(session));
    }

    res.status(200).json({
      ok: true,
      uploadId: uploadData.id,
      status: uploadData.status,
    });
  } catch (error) {
    res.status(500).json({
      error: error instanceof Error ? error.message : "Unexpected Strava upload failure.",
    });
  }
}
